#!/bin/sh

. /etc/os-release
. /lib/functions/uci-defaults.sh

[ $(uname -m) = "x86_64" ] && alias board_name="echo x86_64"
[ "$OPENWRT_BOARD" = "armsr/armv8" ] && alias board_name="echo armsr,armv8"

# OTA
case "$VERSION_TYPE" in
  minimal)
    suffix="-minimal"
    ;;
  standard)
    suffix="-standard"
    ;;
  *)
    suffix=""
    ;;
esac
OTA_URL="https://api.cooluc.com/ota/openwrt-25.12${suffix}.json"

kernel_version=$(uname -r | sed 's/-.*//' | cut -d. -f1-2)

devices_setup()
{
    case "$(board_name)" in
    armsr,armv8)
        if [ "$kernel_version" = "6.18" ]; then
            [ ! -d "/usr/share/openwrt_core" ] && {
                openwrt_core="openwrt_core3/armsr-armv8"
                sed -i '/targets/d' /etc/apk/repositories.d/distfeeds.list
                echo "https://raw.githubusercontent.com/sbwml/${openwrt_core}/$(grep kernel /etc/apk/world | awk -F= '{print $2}')/packages.adb" >> /etc/apk/repositories.d/distfeeds.list
            }
            uci set ota.config.api_url="$OTA_URL"
            uci commit ota
        fi
        ;;
    friendlyarm,nanopi-r4s|\
    friendlyarm,nanopi-r5c|\
    friendlyarm,nanopi-r5s|\
    friendlyarm,nanopi-r76s)
        uci set irqbalance.irqbalance.enabled='0'
        uci commit irqbalance
        service irqbalance stop
        if [ "$kernel_version" = "6.18" ]; then
            [ ! -d "/usr/share/openwrt_core" ] && {
                sed -i '/targets/d' /etc/apk/repositories.d/distfeeds.list
                echo "https://core3.cooluc.com/aarch64_generic/$(grep kernel /etc/apk/world | awk -F= '{print $2}')/packages.adb" >> /etc/apk/repositories.d/distfeeds.list
            }
            uci set ota.config.api_url="$OTA_URL"
            uci commit ota
        fi
        ;;
    x86_64)
        if [ "$kernel_version" = "6.18" ]; then
            [ ! -d "/usr/share/openwrt_core" ] && {
                sed -i '/targets/d' /etc/apk/repositories.d/distfeeds.list
                echo "https://core3.cooluc.com/x86_64/$(grep kernel /etc/apk/world | awk -F= '{print $2}')/packages.adb" >> /etc/apk/repositories.d/distfeeds.list
            }
        fi
        uci set ota.config.api_url="$OTA_URL"
        uci commit ota
        ;;
    esac
}

# theme
if [ -d "/www/luci-static/argon" ] && [ -z "$(uci -q get luci.main.pollinterval)" ]; then
    uci set luci.main.mediaurlbase='/luci-static/argon'
    uci set luci.main.pollinterval='3'
    uci commit luci
fi

# Set argon config
uci set argon.@global[0].mode='dark'
uci set argon.@global[0].transparency='0.5'
uci set argon.@global[0].transparency_dark='0.5'
uci commit argon

# ttyd
uci set ttyd.@ttyd[0].command='/bin/login -f root'
uci commit ttyd
/etc/init.d/ttyd restart

# vlmcsd设置
uci set vlmcsd.@vlmcsd[0].enabled='1'
uci set vlmcsd.@vlmcsd[0].autoactivate='1'
uci set vlmcsd.@vlmcsd[0].firewall='1'

# timezone
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

# log level
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system

# zram
mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
zram_size=$(awk "BEGIN {print int($mem_total*0.25/1024)}")
uci set system.@system[0].zram_size_mb="$zram_size"
uci set system.@system[0].zram_comp_algo='lz4'
uci commit system

# apk mirror
distfeeds=/etc/apk/repositories.d/distfeeds.list
if [ $(grep -c SNAPSHOT "$distfeeds") -eq '0' ]; then
  sed -i 's,downloads.openwrt.org,mirrors.cloud.tencent.com/openwrt,g' "$distfeeds"
else
  sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' "$distfeeds"
fi

# extra packages
echo "https://opkg.cooluc.com/openwrt-25.12/$(cat /etc/apk/arch)/packages.adb" >> "$distfeeds"

# nginx
uci set nginx.global.uci_enable='true'
uci del nginx._lan
uci del nginx._redirect2ssl
uci add nginx server
uci rename nginx.@server[0]='_lan'
uci set nginx._lan.server_name='_lan'
uci add_list nginx._lan.listen='80 default_server'
uci add_list nginx._lan.listen='[::]:80 default_server'
#uci add_list nginx._lan.include='restrict_locally'
uci add_list nginx._lan.include='conf.d/*.locations'
uci set nginx._lan.access_log='off; # logd openwrt'
uci commit nginx
service nginx restart

# docker mirror
if [ -f /etc/config/dockerd ] && [ $(grep -c daocloud.io /etc/config/dockerd) -eq '0' ]; then
    uci add_list dockerd.globals.registry_mirrors="https://docker.m.daocloud.io"
    uci commit dockerd
fi

# firewall
[ $(grep -c shortcut_fe /etc/config/firewall) -eq '0' ] && uci set firewall.@defaults[0].flow_offloading='1'
if [ "$(ip link show | grep -c '^.*: eth')" -le 1 ] || [ "$OPENWRT_BOARD" = "armsr/armv8" ]; then
    uci set firewall.@zone[1].input='ACCEPT'
fi
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall

# diagnostics
if [ $(uci -q get luci.diag.ping) = "openwrt.org" ]; then
    uci set luci.diag.dns='www.qq.com'
    uci set luci.diag.ping='www.qq.com'
    uci set luci.diag.route='www.qq.com'
    uci commit luci
fi

# packet steering
case "$(board_name)" in
friendlyarm,nanopi-r76s)
    uci set network.globals.packet_steering='0'
    ;;
*)
    uci set network.globals.packet_steering=2
    uci set network.globals.steering_flows='128'
    ;;
esac
uci commit network

# disable coremark
sed -i '/coremark/d' /etc/crontabs/root
crontab /etc/crontabs/root

# ==========================================================
# Network / LAN settings
# LAN static IP: 192.168.1.10
# Main router gateway: 192.168.1.1
# ==========================================================

uci -q set network.lan=interface
uci -q set network.lan.proto='static'
uci -q set network.lan.device='eth0'
uci -q set network.lan.ipaddr='192.168.1.10'
uci -q set network.lan.netmask='255.255.255.0'
uci -q set network.lan.gateway='192.168.1.1'
uci -q set network.lan.force_link='1'
uci -q set network.lan.defaultroute='1'

# Disable IPv6 delegation / IPv6 prefix assignment on LAN
uci -q set network.lan.delegate='0'
uci -q delete network.lan.ip6assign

uci -q commit network


# ==========================================================
# DHCP / DNS - dnsmasq settings
# dnsmasq DNS port: 1745
# AdGuardHome should listen on port 53
# ==========================================================

uci -q set dhcp.@dnsmasq[0]=dnsmasq

# Basic DNS / local domain
uci -q set dhcp.@dnsmasq[0].domainneeded='1'
uci -q set dhcp.@dnsmasq[0].localise_queries='1'
uci -q set dhcp.@dnsmasq[0].rebind_protection='1'
uci -q set dhcp.@dnsmasq[0].rebind_localhost='1'
uci -q set dhcp.@dnsmasq[0].local='/lan/'
uci -q set dhcp.@dnsmasq[0].domain='lan'
uci -q set dhcp.@dnsmasq[0].expandhosts='1'

# Move dnsmasq DNS away from 53, let AdGuardHome use 53
uci -q set dhcp.@dnsmasq[0].port='1745'

# Disable DNS cache
uci -q set dhcp.@dnsmasq[0].cachesize='0'
uci -q delete dhcp.@dnsmasq[0].min_cache_ttl
uci -q set dhcp.@dnsmasq[0].max_cache_ttl='3600'

# DNS query / EDNS limits
uci -q set dhcp.@dnsmasq[0].dhcpleasemax='150'
uci -q set dhcp.@dnsmasq[0].ednspacket_max='1232'
uci -q set dhcp.@dnsmasq[0].dnsforwardmax='150'

# Do not read system resolv file
uci -q set dhcp.@dnsmasq[0].noresolv='1'
uci -q set dhcp.@dnsmasq[0].strictorder='0'

# Hosts / ethers / lease files
uci -q set dhcp.@dnsmasq[0].readethers='1'
uci -q set dhcp.@dnsmasq[0].leasefile='/tmp/dhcp.leases'
uci -q set dhcp.@dnsmasq[0].nohosts='0'
uci -q set dhcp.@dnsmasq[0].addnhosts='/etc/dnsmasq.hosts'

# Security / local service
uci -q set dhcp.@dnsmasq[0].localservice='1'

# DNSSEC disabled
uci -q set dhcp.@dnsmasq[0].dnssec='0'
uci -q set dhcp.@dnsmasq[0].dnsseccheckunsigned='0'

# Logging
uci -q set dhcp.@dnsmasq[0].logqueries='0'
uci -q set dhcp.@dnsmasq[0].logdhcp='0'
uci -q set dhcp.@dnsmasq[0].quietdhcp='1'

# Misc switches from screenshots
uci -q set dhcp.@dnsmasq[0].authoritative='0'
uci -q set dhcp.@dnsmasq[0].allservers='0'
uci -q set dhcp.@dnsmasq[0].sequential_ip='0'
uci -q set dhcp.@dnsmasq[0].nonwildcard='0'

# Static DNS address mapping:
# router.local / router.lan -> 192.168.1.1
uci -q delete dhcp.@dnsmasq[0].address
uci -q add_list dhcp.@dnsmasq[0].address='/router.local/router.lan/192.168.1.1'

uci -q commit dhcp

# init
devices_setup

# clean
rm -rf /etc/profile.d/busybox-history-file.sh

exit 0
